### ISSUE TITLE
Transonic Vision link in README is broken

### ISSUE THREAD

**Issue by rgommers** [fluiddyn/transonic#12]
That link still points to Bitbucket (https://fluiddyn.bitbucket.io/transonic-vision.html).

**Comment by paugier** [comment]
Thanks @rgommers ! It's finally fixed in https://github.com/fluiddyn/transonic/commit/3f2fb1e7e68534f7563406046d052941e34e8ab7

**Comment by rgommers** [comment]
Thanks!

**Comment by rgommers** [comment]
Note that it's still wrong in the latest deployed docs (https://transonic.readthedocs.io/en/latest/#the-long-term-project). You probably know that, just mentioning now because of the SciPy discussion on introducing Pythran, which may drive some traffic.
